# Generated by Django 4.2.6 on 2023-10-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empolyee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empolyee_name', models.CharField(blank=True, max_length=100)),
                ('department_id', models.PositiveIntegerField(blank=True)),
                ('department_name', models.CharField(blank=True, max_length=100)),
                ('salary', models.PositiveIntegerField(blank=True)),
            ],
        ),
    ]
